[package]
name = "yaar"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
env_logger = "0.10.0"
hex = "0.4.3"
indexmap = { version = "1.9.3", features = ["serde"] }
itertools = "0.10.5"
log = "0.4.18"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
xrandr = "0.1.1"
